added support for EBS Volume name

diff --git a/tools/ebs b/tools/ebs
--- a/tools/ebs
+++ b/tools/ebs
@@ -2,7 +2,8 @@ usage(){
   echo 
   echo "Environment Variables"
   echo "  DEVICE_ID: Block device mapping (Default /dev/xvdf)"
-  echo "  VOLUME_ID: The ID of the AWS volume (example vol-xxxxxxxx) Required"
+  echo "  VOLUME_ID: The ID of the AWS volume (example vol-xxxxxxxx) Required or VOLUME_NAME"
+  echo "  VOLUME_NAME: The Tag Name of the AWS volume (example Bob) Required or VOLUME_ID"
   echo "Docs - http://docs.aws.amazon.com/cli/latest/reference/ec2/attach-volume.html"
 }
 
@@ -17,20 +18,38 @@ volume_state()
   aws ec2 describe-volumes --volume-id ${VOLUME_ID} --query 'Volumes[].State' --output text
 }
 
+query_id(){
+  AVAILABLITY_ZONE=$(curl -s --fail http://169.254.169.254/latest/dynamic/instance-identity/document | awk -F\" '/availabilityZone/ {print $4}')
+  aws ec2 describe-volumes --query 'Volumes[].[VolumeId]' \
+    --filters "Name=tag:Name,Values=${1}" \
+              "Name=availability-zone,Values=${AVAILABLITY_ZONE}" \
+              "Name=status,Values=available" \
+    --output text | head -n 1
+}
+
 run(){
   METADATA_URL='http://169.254.169.254/latest/meta-data/'
   DEVICE_ID=${DEVICE_ID:-'/dev/xvdf'}
   export AWS_DEFAULT_REGION=$(curl -s --fail http://169.254.169.254/latest/dynamic/instance-identity/document | awk -F\" '/region/ {print $4}')
 
   if [ -z "$VOLUME_ID" ]; then 
-    echo 'VOLUME_ID must be set'; 
-    exit 1 
+    if [ -n "$VOLUME_NAME" ]; then
+      VOLUME_ID=$(query_id $VOLUME_NAME)
+      if [ -z "$VOLUME_ID" ]; then
+        echo "Unable to find volume name for TAG:NAME [$VOLUME_NAME] that is in the available state in current availability zone"
+        exit 1
+      fi
+    else
+      echo 'VOLUME_ID or VOLUME_NAME must be set'; 
+      exit 1 
+    fi
   fi
 
   INSTANCE=$(curl --fail ${METADATA_URL}instance-id 2> /dev/null)
   if [[ $(volume_state) == 'available' ]]; then
     aws ec2 attach-volume --instance-id ${INSTANCE}  --device ${DEVICE_ID} --volume-id ${VOLUME_ID} > /dev/null
     while [ $(volume_state) != 'in-use' ]; do sleep 1; done
+    echo "Attached ${VOLUME_ID}"
   else
     ATTACHED_INSTANCE=$(attached_instance)
     if [[ "$ATTACHED_INSTANCE" == "$INSTANCE" ]]; then
